package common

type ZfInfolist struct {
	Id                int    `json:"id"`
	Siteid            int    `json:"siteid"`
	Classid           int    `json:"classid"`
	Parentid          int    `json:"parentid"`
	Parentstr         string `json:"parentstr"`
	Mainid            int    `json:"mainid"`
	Mainpid           int    `json:"mainpid"`
	Mainpstr          string `json:"mainpstr"`
	Title             string `json:"title"`
	Colorval          string `json:"colorval"`
	Boldval           string `json:"boldval"`
	Flag              string `json:"flag"`
	Source            string `json:"source"`
	Author            string `json:"author"`
	Linkurl           string `json:"linkurl"`
	Keywords          string `json:"keywords"`
	Description       string `json:"description"`
	Content           string `json:"content"`
	ContentText       string `json:"contenttext"`
	Picurl            string `json:"picurl"`
	Picarr            string `json:"picarr"`
	Hits              int    `json:"hits"`
	Orderid           int    `json:"orderid"`
	Posttime          int    `json:"posttime"`
	Checkinfo         string `json:"checkinfo"`
	Delstate          string `json:"delstate"`
	Deltime           int    `json:"deltime"`
	Live_prov         int    `json:"live_prov"`
	Live_city         int    `json:"live_city"`
	Live_country      string `json:"live_country"`
	Zc_type           int    `json:"zc_type"`
	Zc_zb             int    `json:"zc_zb"`
	N_se              int    `json:"n_se"`
	J_zc              int    `json:"j_zc"`
	Zc_ze             int    `json:"zc_ze"`
	Ss_qk             int    `json:"ss_qk"`
	Gx_jsqy           int    `json:"gx_jsqy"`
	Hy_ly             int    `json:"hy_ly"`
	Hy_ly2            string `json:"hy_ly2"`
	Z_tz              int    `json:"z_tz"`
	Zs_cq             int    `json:"zs_cq"`
	Jb                int    `json:"jb"`
	Bw                int    `json:"bw"`
	Cy                int    `json:"cy"`
	Cy2               string `json:"cy2"`
	Td_gm             int    `json:"td_gm"`
	Jsjd_zq           int    `json:"jsjd_zq"`
	Spsx              int    `json:"spsx"`
	Ry_zc             int    `json:"ry_zc"`
	Year              int    `json:"year"`
	Zm                string `json:"zm"`
	Zm_order          int    `json:"zm_order"`
	Ckkj              int    `json:"ckkj"`
	Rzhdk             int    `json:"rzhdk"`
	Qhdq              int    `json:"qhdq"`
	Implement_country string `json:"implement_country"`
	Implement_city    string `json:"implement_city"`
	Implement         int    `json:"implement"`
	Taxes_country     string `json:"taxes_country"`
	Taxes_city        string `json:"taxes_city"`
	Taxes             int    `json:"taxes"`
	Start_time        int    `json:"start_time"`
	End_time          int    `json:"end_time"`
	Zcfx              string `json:"zcfx"`
	Zced              string `json:"zced"`
	Sblc              string `json:"sblc"`
	Zgbm              string `json:"zgbm"`
	Sbsj              string `json:"sbsj"`
	Zlxq              string `json:"zlxq"`
	Jshz              string `json:"jshz"`
	Sfbz              string `json:"sfbz"`
	Jfsj              string `json:"jfsj"`
	Bggs              string `json:"bggs"`
	Shfw              string `json:"shfw"`
	Lxr               string `json:"lxr"`
	Zxdh              string `json:"zxdh"`
	Gjz               string `json:"gjz"`
	Qy_prov           string `json:"qy_prov"`
	Qy_city           string `json:"qy_city"`
	Qy_country        string `json:"qy_country"`
	Stime             int    `json:"stime"`
	Etime             int    `json:"etime"`
	Extended_cid2     int    `json:"extended_cid2"`
	Ym                int    `json:"ym"`
	Registertime      int    `json:"registertime"`
	Extended_cid      int    `json:"extended_cid"`
	N_sesymbol        string `json:"n_sesymbol"`
	Zc_zesymbol       string `json:"zc_zesymbol"`
	Z_tzsymbol        string `json:"z_tzsymbol"`
	Zc_zbsymbol       string `json:"zc_zbsymbol"`
	Td_gm_zesymbol    string `json:"td_gm_zesymbol"`
	J_zcsymbol        string `json:"j_zcsymbol"`
	Week_time         int    `json:"week_time"`
	Month_time        int    `json:"month_time"`
	Season_time       int    `json:"season_time"`
}
type ZFInfoClass struct {
	Id          int    `json:"id"`
	Siteid      int    `json:"siteid"`
	Parentid    int    `json:"parentid"`
	Parentstr   string `json:"parentstr"`
	Infotype    int    `json:"infotype"`
	Classname   string `json:"classname"`
	Linkurl     string `json:"linkurl"`
	Picurl      string `json:"picurl"`
	Picwidth    string `json:"picwidth"`
	Picheight   string `json:"picheight"`
	Seotitle    string `json:"seotitle"`
	Keywords    string `json:"keywords"`
	Description string `json:"description"`
	Orderid     int    `json:"orderid"`
	Checkinfo   string `json:"checkinfo"`
}
type ZFAdminPrivacy struct {
	Groupid int    `json:"groupid"`
	Siteid  int    `json:"siteid"`
	Model   string `json:"model"`
	Classid int    `json:"classid"`
	Action  string `json:"action"`
}
